#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/bspwm/scripts/launch_polybar.sh &
picom &

feh --bg-scale ~/.wallpaper/drakon_klassika_svet_16050_1920x1080.jpg

firefox &
telegram-desktop -startintray &



#
bspc monitor -d I II III IV V VI  


#
bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"
bspc config presel_feedback_color "#23252e"


#

bspc config focus_follows_pointer true
bspc config pointer_modifier	super


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a firefox state=floating rectangle=1600x900+160+90 desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off

